name: RTL LINT

on:
  push:
  pull_request:

jobs:
  lint-and-synth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install verilator
        run: |
          sudo apt update
          sudo apt install verilator

      - name: Check Verilator Version
        run: verilator --version

      - name: Run Verilator Lint
        run: |
          chmod +x scripts/lint_rtl.sh
          ./scripts/lint_rtl.sh             
          chmod +x scripts/lint_bfm.sh
          ./scripts/lint_bfm.sh
        
      - name: Print lint logs if exist
        if: always()
        run: |
            echo "---- RTL LINT LOG ----"
            cat scripts/lint_rtl.log || true
            echo "---- BFM LINT LOG ----"
            cat scripts/lint_bfm.log || true
            
