name: RTL CI

on:
  push:
  pull_request:

jobs:
  lint-and-synth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show directory structure
        run: tree -L 2

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y  yosys

      - name: Install Verilator 5.045 (exact local version)
        run: |
          sudo apt update
          sudo apt install -y git make autoconf g++ flex bison libfl-dev
        
          git clone https://github.com/verilator/verilator.git
          cd verilator
      
          git checkout 1dd80996c
      
          autoconf
          ./configure
          make -j$(nproc)
          sudo make install
        
          verilator --version

      - name: Check Verilator Version
        run: verilator --version

      - name: Run Verilator Lint
        run: |
          chmod +x scripts/lint_rtl.sh
          ./scripts/lint_rtl.sh             
          chmod +x scripts/lint_bfm.sh
          ./scripts/lint_bfm.sh
        
      - name: Print lint logs if exist
        if: always()
        run: |
            echo "---- RTL LINT LOG ----"
            cat scripts/lint_rtl.log || true
            echo "---- BFM LINT LOG ----"
            cat scripts/lint_bfm.log || true
            
      - name: Run Yosys Synthesis
        run: |
          chmod +x scripts/syn_nangate45.sh
          ./scripts/syn_nangate45.sh
